apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: laszlo-app-operator
  namespace: default
spec:
  values:
    image:
      repository: gsoci.azurecr.io/giantswarm/app-operator # {"$imagepolicy": "default:laszlo-app-operator:name"}
      tag: 4.0.6 # {"$imagepolicy": "default:laszlo-app-operator:tag"}
      digest: sha256:6129bb944cada32b4662eafd13fd9904d34c77286bf2ec4523eaedb711757cb0 # {"$imagepolicy": "default:laszlo-app-operator:digest"}
